In [1]:
import pandas as pd
import numpy as np

In [3]:
x = np.arange(10,50,10)
x

array([10, 20, 30, 40])

In [7]:
df = pd.Series(x)
df

0    10
1    20
2    30
3    40
dtype: int64

In [8]:
df.dtype

dtype('int64')

In [14]:
index = ['a','b','c','d']
s = pd.Series(x,index)
s

a    10
b    20
c    30
d    40
dtype: int64

In [48]:
s[4]=1
s

a    20
b    20
c    30
d    40
e     1
dtype: int64

In [41]:
s.axes

[Index(['a', 'b', 'c', 'd', 'e'], dtype='object')]

In [42]:
s.values

array([20, 20, 30, 40,  1])

In [43]:
s.size

5

In [44]:
s.shape

(5,)

In [45]:
s.ndim

1

In [46]:
s.dtype

dtype('int64')

In [49]:
s["e"] = 50
s

a    20
b    20
c    30
d    40
e    50
dtype: int64

In [33]:
data = {'a':10,'b':20,'c':40,'d':50}
pd.Series(data)

a    10
b    20
c    40
d    50
dtype: int64

In [34]:
pd.Series(['a','b','c','d','e'])

0    a
1    b
2    c
3    d
4    e
dtype: object

In [62]:
x = [[10, 20, 30, 40],[50, 60, 70, 80]]
df = pd.DataFrame(x,['a', 'b'],['A','B','C','D'])
df

A   B   C   D
a  10  20  30  40
b  50  60  70  80

In [64]:
df['A']['a']

10

In [67]:
df.values

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [68]:
df.mean()

A    30.0
B    40.0
C    50.0
D    60.0
dtype: float64

In [69]:
df.max()

A    50
B    60
C    70
D    80
dtype: int64

In [70]:
df.std()

A    28.284271
B    28.284271
C    28.284271
D    28.284271
dtype: float64

In [71]:
df.var()

A    800.0
B    800.0
C    800.0
D    800.0
dtype: float64

In [72]:
df

A   B   C   D
a  10  20  30  40
b  50  60  70  80

In [82]:
df.iloc[:,1:3]

B   C
a  20  30
b  60  70

In [91]:
D1=pd.DataFrame([[-1,0,-2],list(np.array(np.random.randint(1,4,3)))],['a','b'],['A','B','C'])
D1

A  B  C
a -1  0 -2
b  1  3  2